### ISSUE TITLE
I encountered some problems logging in to the page:http://127.0.0.1:8000/accounts/login/

### ISSUE THREAD

**Issue by xiaoyingjiejie** [adilmohak/django-lms#26]
What's my id number and keyword?
DB_NAME=student grade
DB_USER=
DB_PASSWORD=
DB_HOST=localhost
DB_PORT=5432
USER_EMAIL=
USER_PASSWORD=
DEBUG=True
SECRET_KEY=

**Comment by RazaSaleem** [comment]
For this xiaoyingjiejie
you need to install the PostgreSQL Database then there it will ask for the initial username and user password, in which you will create DB with any name you want and DB_USER and DB_PASSWORD, after having that database you have to create a superuser for yourself self to login



`python manage.py createsuperuser`

after this command in your terminal, it will as you the username and password those will be your user ID and password for signing in.

**Comment by adilmohak** [comment]
Thank you @RazaSaleem 
@xiaoyingjiejie let us know if you need further help.

**Comment by xiaoyingjiejie** [comment]
> 对于这个 xiaoyingjiejie， 你需要安装 PostgreSQL 数据库，然后它会要求输入初始用户名和用户密码，在其中你将使用你想要的任何名称以及 DB_USER 和 DB_PASSWORD 创建数据库，在拥有该数据库之后，你必须为其创建一个超级用户自己自行登录
> 
> `python manage.py createsuperuser`
> 
> 在终端中执行此命令后，它将作为您的用户名和密码，这些将是您用于登录的用户 ID 和密码。

Thank you very much! I got it.  If the writer can write this step into the readme, it will avoid the problems that arise for beginners like me.

**Comment by xiaoyingjiejie** [comment]
> 谢谢@RazaSaleem @xiaoyingjiejie如果您需要进一步的帮助，请告诉我们。

Honestly, this program is very useful for me as an English teacher. And I am very interested in python. There is another question:
[6班期中期末考试成绩.xlsx](https://github.com/adilmohak/django-lms/files/14173934/6.xlsx)
[副本6班期中期末考试成绩.csv](https://github.com/adilmohak/django-lms/files/14173935/6.csv)

 How do I add student names and grades in bulk, via Python or PostgreSQL, or via Django Web? Could
 you please help me?

**Comment by adilmohak** [comment]
Bulk insertion is currently not supported.

**Comment by xiaoyingjiejie** [comment]
> 目前不支持批量插入。

Thanks. Could you tell me why you didn't develop such a feature, and would you consider adding this feature in the future? As a teacher, I need to add all students' grade score to analyse them by this program.

**Comment by adilmohak** [comment]
Bulk insertion by means using a CSV/excel file to create multiple students? And also using CSV/excel to submit their results/scores?
