### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by abinkrishna10** [adilmohak/django-lms#3]
(venv) PS D:\project\django-lms-main> python manage.py makemigrations
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\django-lms-main\venv\Lib\site-packages\django\apps\config.py", line 228, in create
    import_module(entry)
  File "C:\Users\snm20\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import     
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load  
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_cleanup'

this error is showing

**Comment by adilmohak** [comment]
Make sure you install requirements, `pip install -r requirements.txt`
If you already install all the requirements make sure you're using the correct environment

**Comment by MokiMeow** [comment]
Request Method: | GET
http://127.0.0.1:8000/accounts/profile/
accounts.views.profile

>

**Comment by MokiMeow** [comment]
Page not found (404)
No Session matches the given query.

Request Method: | GET
Request URL: | http://127.0.0.1:8000/accounts/profile/
Raised by: | accounts.views.profile


i am facing this issue i cant acces the profile y??

**Comment by MokiMeow** [comment]
and also add quiz is not showing do we need to add subject to use it? 

hope u help me to solve these 2 problems

**Comment by deepakbhat9414** [comment]
Can you do the video of how to connect database

**Comment by adilmohak** [comment]
> Page not found (404) No Session matches the given query.
> 
> Request Method: | GET Request URL: | http://127.0.0.1:8000/accounts/profile/ Raised by: | accounts.views.profile
> 
> i am facing this issue i cant acces the profile y??

In order to access the profile page you need to login first

**Comment by adilmohak** [comment]
> and also add quiz is not showing do we need to add subject to use it?
> 
> hope u help me to solve these 2 problems

Yes, you need to create a subject first, because each quiz is associated with a subject/course

**Comment by adilmohak** [comment]
> (venv) PS D:\project\django-lms-main> python manage.py makemigrations app_config = AppConfig.create(entry) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\project\django-lms-main\venv\Lib\site-packages\django\apps\config.py", line 228, in create import_module(entry) File "C:\Users\snm20\AppData\Local\Programs\Python\Python311\Lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1142, in _find_and_load_unlocked ModuleNotFoundError: No module named 'django_cleanup'
> 
> this error is showing

I just forgot to include `django_cleanup` and other requirements such as `reportlab`, `stripe`, and `gopay`. Try to pull the latest version of the project and run it, it should work fine now.
