### ISSUE TITLE
Profile Page Not Working

### ISSUE THREAD

**Issue by anand-3399** [adilmohak/django-lms#4]
The profile page is not working despite of logging. I have logged in with admin id and pw and the profile page is not at all working. It says page not found. Below I have attached some of the screenshots of it.

![image](https://github.com/adilmohak/django-lms/assets/85798085/87f11a12-50e4-45c6-816c-e6f7557c2da9)

![image](https://github.com/adilmohak/django-lms/assets/85798085/501c9bd4-2744-43e0-a98d-a1473e379dfa)

Please look to it if there is any typo in code.

**Comment by adilmohak** [comment]
Before accessing the profile page you need to create at least one `session` and one `semester`, that's why you're getting 404 error

**Comment by adilmohak** [comment]
I just fixed the 404 error, it should work fine now
