### ISSUE TITLE
Error in the accounts.forms.py

### ISSUE THREAD

**Issue by dokuch1977** [adilmohak/django-lms#43]
https://github.com/adilmohak/django-lms/blob/776b9120e8e66ce5f22275611a93be68a5182c17/accounts/forms.py#L140

 line 140 you need "settings.EMAIL_FROM_ADDRESS" instead of "from@example.com",

**Comment by adilmohak** [comment]
Since this issue is not clear I'll close it. If there is something we can help you please let us know in a more detailed manner.
