### ISSUE TITLE
Project Sustainability

### ISSUE THREAD

**Issue by Whizfactor** [adilmohak/django-lms#5]
You would need more maintainers for this to work. It looks nice but lacks enough maintainers to ensure the long term relevance and updatedness of the project. How do you intend to tackle this? You interested in having developers on board with you?

**Comment by Whizfactor** [comment]
Why not make this a django app that can be installed using pip?

**Comment by adilmohak** [comment]
Hi @Whizfactor, 
sorry for my delayed reply. 
I think your suggestion about having more maintainers and developers is a great idea. As I mentioned in the project readme file, I am completely open to collaboration to improve the project.
