### ISSUE TITLE
Quiz Edit

### ISSUE THREAD

**Issue by TSmiley12** [adilmohak/django-lms#7]
Editing and deletion of quiz not displaying for lectures who created it

**Comment by adilmohak** [comment]
Hey @TSmiley12,
Thank you for bringing up this issue. The problem was just on the UI design and it has been resolved now. 
Please let me know if there is anything else I can help you with.
Feel free to close this issue if you think it is resolved.

**Comment by WajahatKanju** [comment]
Please close the issue if it has been resolved. @adilmohak
