### ISSUE TITLE
SECRET_KEY is hardcoded in the config/settings.py file

### ISSUE THREAD

**Issue by benaissazaki** [adilmohak/django-lms#9]
**Is your feature request related to a problem? Please describe.**
The SECRET_KEY setting's value is hardcoded in the settings.py file which is a bad practice in Django as it could have many security implications.

**Describe the solution you'd like**
Make the SECRET_KEY an environment variable and decouple it from the code as it is already the case for DEBUG or DB_NAME.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by adilmohak** [comment]
Hey @benaissazaki,
I appreciate you pointing this out. I'll make sure to update it accordingly.

**Comment by adilmohak** [comment]
It is now using an environment variable to store the SECRET_KEY securely.

**Comment by adilmohak** [comment]
Feel free to close this issue

**Comment by benaissazaki** [comment]
I would like
